<a href="https://colab.research.google.com/github/Amir-Ali-Peymani/ML-practice/blob/main/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## importing numpy


In [1]:
import numpy as np

Lets to some basic stuff

In [4]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3, 5)
2
15
int64


In [16]:
 a = np.arange(20)
 a = a.reshape(5,4)
 b = np.arange(20)
 b = b.reshape(4,5)
a@b

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462],
       [430, 484, 538, 592, 646],
       [550, 620, 690, 760, 830]])